---
  - name: Ensure cpu-checker is remove to run kvm-ok
    apt:
      name: cpu-checker=0.7-0ubuntu7
      autoremove: yes
      state: absent
      purge: yes
  - name: Ensure qemu-kvm is purged
    apt:
      name: qemu-kvm=1:2.5+dfsg-5ubuntu10
      autoremove: yes
      state: absent
      purge: yes
  - name: Ensure libvirt-bin is purged
    apt:
      name: libvirt-bin=1.3.1-1ubuntu10
      autoremove: yes
      state: absent
      purge: yes
  - name: Ensure ubuntu-vm-builder is purged
    apt:
      name: ubuntu-vm-builder=0.12.4+bzr494-0ubuntu1
      autoremove: yes
      state: absent
      purge: yes

  - name: Ensure bridge-utils is purged
    apt:
      name: bridge-utils=1.5-9ubuntu1
      autoremove: yes
      state: absent
      purge: yes
  - name: Ensure virtinst is purged
    apt:
      name: virtinst
      autoremove: yes
      state: absent
      purge: yes

  - name: Ensure virt-manager is purged
    apt:
      name: virt-manager
      autoremove: yes
      state: absent
      purge: yes
  - name: Ensure python-virtinst is purged
    apt:
      name: python-virtinst
      autoremove: yes
      state: absent
      purge: yes
