---
  - name: Ensure cpu-checker is remove to run kvm-ok
    apt:
      name: cpu-checker=0.7-0ubuntu7
      autoremove: yes
      state: absent
      purge: yes
  - name: Ensure qemu-kvm is installed
    apt:
      name: qemu-kvm=1:2.5+dfsg-5ubuntu10
      autoremove: yes
      state: absent
      purge: yes
  - name: Ensure libvirt-bin is installed
    apt:
      name: libvirt-bin=1.3.1-1ubuntu10
      autoremove: yes
      state: absent
      purge: yes
  - name: Ensure ubuntu-vm-builder is installed
    apt:
      name: ubuntu-vm-builder=0.12.4+bzr494-0ubuntu1
      autoremove: yes
      state: absent
      purge: yes

  - name: Ensure bridge-utils is installed
    apt:
      name: bridge-utils=1.5-9ubuntu1
      autoremove: yes
      state: absent
      purge: yes
