---
  # Installation guide from: https://repo.saltstack.com/
 # - name: Ensure saltstack repo for ubuntu is in place
#    apt_repository:
#      filename: /etc/apt/sources.list.d/saltstack.list
#      repo: deb http://repo.saltstack.com/apt/ubuntu/16.04/amd64/latest xenial main
#      mode: 420
#      state: present
#      update_cache: yes
#      validate_certs: yes
 # - name: Ensure gpg key is imported
#    command: "wget -O - https://repo.saltstack.com/apt/ubuntu/16.04/amd64/latest/SALTSTACK-GPG-KEY.pub | sudo apt-key add -"

  - name: Ensure saltstack repo for ubuntu is in place
    template: src="saltstack.list.j2" dest="/etc/apt/sources.list.d/saltstack.list" owner="root" mode="0644"

  - name: Install saltstack packages
    apt:
      name: "{{item}}"
      update_cache: no
    with_items: "{{packages}}"
