---
  # Print out the current image metadata
  - name: Debug current image data
    debug:
      msg: "Downloading {{item}}"

  # Download current image,
  #   item.url.split('/')[-1] will get the last part of the url, which is the
  #   name of the image file.
  - name: Download image and check the SHA256SUM
    get_url:
      url: "{{item.url}}"
      checksum: "{{item.alg}}:{{item.hash}}"
      dest: "{{image_location}}/{{item.url.split('/')[-1]}}"
      timeout: "{{timeout}}"
      owner: "{{user}}"
